# Generated by Django 5.0.2 on 2024-02-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='forward_email',
            new_name='admin_email',
        ),
    ]
