# Generated by Django 5.0.2 on 2024-02-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
